config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'blog#home'
  get 'blog/home' => 'blog#home'
  get 'blog/about' => 'blog#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def home
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog/about.html.erb
<html>
    <head>
        <title>Rails Test App</title>
        <%= stylesheet_link_tag 'homepage', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="page">
            <div class="header">
                <div class="title">
                    <h1>RAILS TEST APP</h1>
                </div>
                <div class="menu">
                    <div class="links">
                        <div class="button">
                            <%= link_to 'HOME', root_path %>
                        </div>
                        <div class="button">
                            <%= link_to 'ABOUT', blog_about_path %>
                        </div>
                    </div>
                </div>

                <div class="title">
                </div>
            </div>

            <div class="content">
                <div class="container left">
                    <div class="text-box">
                        SOMETHING SOMETHING
                    </div>
                </div>
                
                <div class="container right">
                    <div class="text-box">
                        THIS IS ABOUT PAGE
                    </div>
                </div>
            </div>

            <div class="footer">
                <div class="footer-content">
                    Copyright ©
                </div>
            </div>
        </div>
    </body>
</html>

app/views/blog/home.html.erb
<html>
    <head>
        <title>Rails Test App</title>
        <%= stylesheet_link_tag 'homepage', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="page">
            <div class="header">
                <div class="title">
                    <h1>RAILS TEST APP</h1>
                </div>
                <div class="menu">
                    <div class="links">
                        <div class="button">
                            <%= link_to 'HOME', root_path %>
                        </div>
                        <div class="button">
                            <%= link_to 'ABOUT', blog_about_path %>
                        </div>
                    </div>
                </div>

                <div class="title">
                </div>
            </div>

            <div class="content">
                <div class="container left">
                    <div class="text-box">
                        THIS IS HOMEPAGE
                    </div>
                </div>
                
                <div class="container right">
                    <div class="text-box">
                        SOMETHING SOMETHING
                    </div>
                </div>
            </div>

            <div class="footer">
                <div class="footer-content">
                    Copyright ©
                </div>
            </div>
        </div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>